name: Feature Request
description: Suggest a new feature for the PaceMan.gg Mobile app
labels: suggestions
body:
  - type: markdown
    attributes:
      value: |
        Please fill out the form below to suggest a new feature for the app.

  - type: textarea
    id: feature_description
    attributes:
      label: Describe the feature you'd like
      description: Provide a clear and concise description of the feature you want to be added.
      placeholder: Describe the feature...
    validations:
      required: true

  - type: textarea
    id: reason_for_feature
    attributes:
      label: Reason for adding this feature
      description: Explain how this feature would enhance the app and benefit users.
      placeholder: How will this feature improve the app?
    validations:
      required: true

  - type: dropdown
    id: platform
    attributes:
      label: Platform
      description: Specify which platform this feature is for.
      options:
        - Android
        - iOS
        - Both
    validations:
      required: true

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: Add any other context, comments, or suggestions regarding this feature request.
      placeholder: Additional comments or suggestions...
